<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsDeploymentTarget>true</IsDeploymentTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" />
    <PackageReference Include="MessagePackAnalyzer" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Everywhere.Abstractions\Everywhere.Abstractions.csproj" />
    <ProjectReference Include="..\Everywhere.ProcessIsolation.SourceGenerator\Everywhere.ProcessIsolation.SourceGenerator.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

</Project>