<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsDeploymentTarget>true</IsDeploymentTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Porta.Pty" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Everywhere.Abstractions\Everywhere.Abstractions.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <InternalsVisibleTo Include="Everywhere.Terminal.Tests" />
    <InternalsVisibleTo Include="Everywhere.Terminal.TestApp" />
  </ItemGroup>

</Project>
