<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsDeploymentTarget>true</IsDeploymentTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack"/>
    <PackageReference Include="MessagePackAnalyzer" PrivateAssets="all"/>
    <PackageReference Include="Microsoft.ML.Tokenizers"/>
    <PackageReference Include="Microsoft.ML.Tokenizers.Data.O200kBase"/>
    <PackageReference Include="ZLinq"/>
  </ItemGroup>

</Project>
