<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Everywhere.I18N</RootNamespace>
    <AvaloniaAccessUnstablePrivateApis>true</AvaloniaAccessUnstablePrivateApis>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia"/>
    <PackageReference Include="CommunityToolkit.Mvvm"/>
    <PackageReference Include="DynamicData"/>
    <PackageReference Include="MessagePack"/>
    <PackageReference Include="MessagePackAnalyzer" PrivateAssets="all"/>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
    <PackageReference Include="ZLinq"/>
  </ItemGroup>

</Project>
